server:
  port: 8081
  context: /
spring:
  dubbo:
    application:
       name: consumer-dubbo
    registry:
       protocol: zookeeper
       address: 172.18.1.112:2181
    protocol:
       name: dubbo
       port: -1
    timeout: 500
    scan: com.demo.controller
